name: Run always devel
# random commit
on:
  push:
    branches:
      - devel
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World called from devel!"
